// Generated by gencpp from file roborts_msgs/ArmorDetection.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_ARMORDETECTION_H
#define ROBORTS_MSGS_MESSAGE_ARMORDETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace roborts_msgs
{
template <class ContainerAllocator>
struct ArmorDetection_
{
  typedef ArmorDetection_<ContainerAllocator> Type;

  ArmorDetection_()
    : header()
    , id(0)
    , detected_enemy(false)
    , enemy_x(0.0)
    , enemy_y(0.0)
    , distance(0.0)  {
    }
  ArmorDetection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , detected_enemy(false)
    , enemy_x(0.0)
    , enemy_y(0.0)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _id_type;
  _id_type id;

   typedef uint8_t _detected_enemy_type;
  _detected_enemy_type detected_enemy;

   typedef double _enemy_x_type;
  _enemy_x_type enemy_x;

   typedef double _enemy_y_type;
  _enemy_y_type enemy_y;

   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::roborts_msgs::ArmorDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::ArmorDetection_<ContainerAllocator> const> ConstPtr;

}; // struct ArmorDetection_

typedef ::roborts_msgs::ArmorDetection_<std::allocator<void> > ArmorDetection;

typedef boost::shared_ptr< ::roborts_msgs::ArmorDetection > ArmorDetectionPtr;
typedef boost::shared_ptr< ::roborts_msgs::ArmorDetection const> ArmorDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::ArmorDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::ArmorDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roborts_msgs::ArmorDetection_<ContainerAllocator1> & lhs, const ::roborts_msgs::ArmorDetection_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id == rhs.id &&
    lhs.detected_enemy == rhs.detected_enemy &&
    lhs.enemy_x == rhs.enemy_x &&
    lhs.enemy_y == rhs.enemy_y &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roborts_msgs::ArmorDetection_<ContainerAllocator1> & lhs, const ::roborts_msgs::ArmorDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::ArmorDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::ArmorDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::ArmorDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::ArmorDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::ArmorDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::ArmorDetection_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::ArmorDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73e2d1a46dbd916f5132a3ac033ec3eb";
  }

  static const char* value(const ::roborts_msgs::ArmorDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73e2d1a46dbd916fULL;
  static const uint64_t static_value2 = 0x5132a3ac033ec3ebULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::ArmorDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/ArmorDetection";
  }

  static const char* value(const ::roborts_msgs::ArmorDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::ArmorDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#armor detected msg\n"
"Header header\n"
"uint8 id\n"
"bool detected_enemy\n"
"float64 enemy_x\n"
"float64 enemy_y\n"
"float64 distance\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::roborts_msgs::ArmorDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::ArmorDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.detected_enemy);
      stream.next(m.enemy_x);
      stream.next(m.enemy_y);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmorDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::ArmorDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::ArmorDetection_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "detected_enemy: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.detected_enemy);
    s << indent << "enemy_x: ";
    Printer<double>::stream(s, indent + "  ", v.enemy_x);
    s << indent << "enemy_y: ";
    Printer<double>::stream(s, indent + "  ", v.enemy_y);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_ARMORDETECTION_H
