# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roborts_msgs/ArmorMsg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class ArmorMsg(genpy.Message):
  _md5sum = "0168548d106cea9b6c2d1718be86c76f"
  _type = "roborts_msgs/ArmorMsg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool robot_detected
bool armor_detected
int8 robot_pose
int8 color # 0 RED 1 BLUE
int8 id # 1 2
int32 area # area of the armor
geometry_msgs/Point pose
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['robot_detected','armor_detected','robot_pose','color','id','area','pose']
  _slot_types = ['bool','bool','int8','int8','int8','int32','geometry_msgs/Point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       robot_detected,armor_detected,robot_pose,color,id,area,pose

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ArmorMsg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.robot_detected is None:
        self.robot_detected = False
      if self.armor_detected is None:
        self.armor_detected = False
      if self.robot_pose is None:
        self.robot_pose = 0
      if self.color is None:
        self.color = 0
      if self.id is None:
        self.id = 0
      if self.area is None:
        self.area = 0
      if self.pose is None:
        self.pose = geometry_msgs.msg.Point()
    else:
      self.robot_detected = False
      self.armor_detected = False
      self.robot_pose = 0
      self.color = 0
      self.id = 0
      self.area = 0
      self.pose = geometry_msgs.msg.Point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B3bi3d().pack(_x.robot_detected, _x.armor_detected, _x.robot_pose, _x.color, _x.id, _x.area, _x.pose.x, _x.pose.y, _x.pose.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose is None:
        self.pose = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 33
      (_x.robot_detected, _x.armor_detected, _x.robot_pose, _x.color, _x.id, _x.area, _x.pose.x, _x.pose.y, _x.pose.z,) = _get_struct_2B3bi3d().unpack(str[start:end])
      self.robot_detected = bool(self.robot_detected)
      self.armor_detected = bool(self.armor_detected)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B3bi3d().pack(_x.robot_detected, _x.armor_detected, _x.robot_pose, _x.color, _x.id, _x.area, _x.pose.x, _x.pose.y, _x.pose.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose is None:
        self.pose = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 33
      (_x.robot_detected, _x.armor_detected, _x.robot_pose, _x.color, _x.id, _x.area, _x.pose.x, _x.pose.y, _x.pose.z,) = _get_struct_2B3bi3d().unpack(str[start:end])
      self.robot_detected = bool(self.robot_detected)
      self.armor_detected = bool(self.armor_detected)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B3bi3d = None
def _get_struct_2B3bi3d():
    global _struct_2B3bi3d
    if _struct_2B3bi3d is None:
        _struct_2B3bi3d = struct.Struct("<2B3bi3d")
    return _struct_2B3bi3d
