# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roborts_msgs/ArmorMsgs.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import roborts_msgs.msg

class ArmorMsgs(genpy.Message):
  _md5sum = "7abd3895cfb29c9d0395c412cceb145f"
  _type = "roborts_msgs/ArmorMsgs"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool detected
ArmorMsg[] detected_info
================================================================================
MSG: roborts_msgs/ArmorMsg
bool robot_detected
bool armor_detected
int8 robot_pose
int8 color # 0 RED 1 BLUE
int8 id # 1 2
int32 area # area of the armor
geometry_msgs/Point pose
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['detected','detected_info']
  _slot_types = ['bool','roborts_msgs/ArmorMsg[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       detected,detected_info

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ArmorMsgs, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.detected is None:
        self.detected = False
      if self.detected_info is None:
        self.detected_info = []
    else:
      self.detected = False
      self.detected_info = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.detected
      buff.write(_get_struct_B().pack(_x))
      length = len(self.detected_info)
      buff.write(_struct_I.pack(length))
      for val1 in self.detected_info:
        _x = val1
        buff.write(_get_struct_2B3bi().pack(_x.robot_detected, _x.armor_detected, _x.robot_pose, _x.color, _x.id, _x.area))
        _v1 = val1.pose
        _x = _v1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.detected_info is None:
        self.detected_info = None
      end = 0
      start = end
      end += 1
      (self.detected,) = _get_struct_B().unpack(str[start:end])
      self.detected = bool(self.detected)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.detected_info = []
      for i in range(0, length):
        val1 = roborts_msgs.msg.ArmorMsg()
        _x = val1
        start = end
        end += 9
        (_x.robot_detected, _x.armor_detected, _x.robot_pose, _x.color, _x.id, _x.area,) = _get_struct_2B3bi().unpack(str[start:end])
        val1.robot_detected = bool(val1.robot_detected)
        val1.armor_detected = bool(val1.armor_detected)
        _v2 = val1.pose
        _x = _v2
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.detected_info.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.detected
      buff.write(_get_struct_B().pack(_x))
      length = len(self.detected_info)
      buff.write(_struct_I.pack(length))
      for val1 in self.detected_info:
        _x = val1
        buff.write(_get_struct_2B3bi().pack(_x.robot_detected, _x.armor_detected, _x.robot_pose, _x.color, _x.id, _x.area))
        _v3 = val1.pose
        _x = _v3
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.detected_info is None:
        self.detected_info = None
      end = 0
      start = end
      end += 1
      (self.detected,) = _get_struct_B().unpack(str[start:end])
      self.detected = bool(self.detected)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.detected_info = []
      for i in range(0, length):
        val1 = roborts_msgs.msg.ArmorMsg()
        _x = val1
        start = end
        end += 9
        (_x.robot_detected, _x.armor_detected, _x.robot_pose, _x.color, _x.id, _x.area,) = _get_struct_2B3bi().unpack(str[start:end])
        val1.robot_detected = bool(val1.robot_detected)
        val1.armor_detected = bool(val1.armor_detected)
        _v4 = val1.pose
        _x = _v4
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.detected_info.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B3bi = None
def _get_struct_2B3bi():
    global _struct_2B3bi
    if _struct_2B3bi is None:
        _struct_2B3bi = struct.Struct("<2B3bi")
    return _struct_2B3bi
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
