// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: a_star_planner_config.proto

#include "a_star_planner_config.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace roborts_global_planner {
PROTOBUF_CONSTEXPR AStarPlannerConfig::AStarPlannerConfig(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.goal_search_tolerance_)*/0.25f
  , /*decltype(_impl_.inaccessible_cost_)*/253u
  , /*decltype(_impl_.heuristic_factor_)*/1} {}
struct AStarPlannerConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AStarPlannerConfigDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AStarPlannerConfigDefaultTypeInternal() {}
  union {
    AStarPlannerConfig _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AStarPlannerConfigDefaultTypeInternal _AStarPlannerConfig_default_instance_;
}  // namespace roborts_global_planner
static ::_pb::Metadata file_level_metadata_a_5fstar_5fplanner_5fconfig_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_a_5fstar_5fplanner_5fconfig_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_a_5fstar_5fplanner_5fconfig_2eproto = nullptr;

const uint32_t TableStruct_a_5fstar_5fplanner_5fconfig_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::roborts_global_planner::AStarPlannerConfig, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::roborts_global_planner::AStarPlannerConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::roborts_global_planner::AStarPlannerConfig, _impl_.inaccessible_cost_),
  PROTOBUF_FIELD_OFFSET(::roborts_global_planner::AStarPlannerConfig, _impl_.heuristic_factor_),
  PROTOBUF_FIELD_OFFSET(::roborts_global_planner::AStarPlannerConfig, _impl_.goal_search_tolerance_),
  1,
  2,
  0,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 9, -1, sizeof(::roborts_global_planner::AStarPlannerConfig)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::roborts_global_planner::_AStarPlannerConfig_default_instance_._instance,
};

const char descriptor_table_protodef_a_5fstar_5fplanner_5fconfig_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\033a_star_planner_config.proto\022\026roborts_g"
  "lobal_planner\"v\n\022AStarPlannerConfig\022\036\n\021i"
  "naccessible_cost\030\001 \001(\r:\003253\022\033\n\020heuristic"
  "_factor\030\002 \001(\002:\0011\022#\n\025goal_search_toleranc"
  "e\030\003 \001(\002:\0040.25"
  ;
static ::_pbi::once_flag descriptor_table_a_5fstar_5fplanner_5fconfig_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_a_5fstar_5fplanner_5fconfig_2eproto = {
    false, false, 173, descriptor_table_protodef_a_5fstar_5fplanner_5fconfig_2eproto,
    "a_star_planner_config.proto",
    &descriptor_table_a_5fstar_5fplanner_5fconfig_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_a_5fstar_5fplanner_5fconfig_2eproto::offsets,
    file_level_metadata_a_5fstar_5fplanner_5fconfig_2eproto, file_level_enum_descriptors_a_5fstar_5fplanner_5fconfig_2eproto,
    file_level_service_descriptors_a_5fstar_5fplanner_5fconfig_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_a_5fstar_5fplanner_5fconfig_2eproto_getter() {
  return &descriptor_table_a_5fstar_5fplanner_5fconfig_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_a_5fstar_5fplanner_5fconfig_2eproto(&descriptor_table_a_5fstar_5fplanner_5fconfig_2eproto);
namespace roborts_global_planner {

// ===================================================================

class AStarPlannerConfig::_Internal {
 public:
  using HasBits = decltype(std::declval<AStarPlannerConfig>()._impl_._has_bits_);
  static void set_has_inaccessible_cost(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_heuristic_factor(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_goal_search_tolerance(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

AStarPlannerConfig::AStarPlannerConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:roborts_global_planner.AStarPlannerConfig)
}
AStarPlannerConfig::AStarPlannerConfig(const AStarPlannerConfig& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AStarPlannerConfig* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.goal_search_tolerance_){}
    , decltype(_impl_.inaccessible_cost_){}
    , decltype(_impl_.heuristic_factor_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.goal_search_tolerance_, &from._impl_.goal_search_tolerance_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.heuristic_factor_) -
    reinterpret_cast<char*>(&_impl_.goal_search_tolerance_)) + sizeof(_impl_.heuristic_factor_));
  // @@protoc_insertion_point(copy_constructor:roborts_global_planner.AStarPlannerConfig)
}

inline void AStarPlannerConfig::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.goal_search_tolerance_){0.25f}
    , decltype(_impl_.inaccessible_cost_){253u}
    , decltype(_impl_.heuristic_factor_){1}
  };
}

AStarPlannerConfig::~AStarPlannerConfig() {
  // @@protoc_insertion_point(destructor:roborts_global_planner.AStarPlannerConfig)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AStarPlannerConfig::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void AStarPlannerConfig::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AStarPlannerConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:roborts_global_planner.AStarPlannerConfig)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    _impl_.goal_search_tolerance_ = 0.25f;
    _impl_.inaccessible_cost_ = 253u;
    _impl_.heuristic_factor_ = 1;
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AStarPlannerConfig::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint32 inaccessible_cost = 1 [default = 253];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_inaccessible_cost(&has_bits);
          _impl_.inaccessible_cost_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional float heuristic_factor = 2 [default = 1];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _Internal::set_has_heuristic_factor(&has_bits);
          _impl_.heuristic_factor_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // optional float goal_search_tolerance = 3 [default = 0.25];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 29)) {
          _Internal::set_has_goal_search_tolerance(&has_bits);
          _impl_.goal_search_tolerance_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AStarPlannerConfig::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:roborts_global_planner.AStarPlannerConfig)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional uint32 inaccessible_cost = 1 [default = 253];
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_inaccessible_cost(), target);
  }

  // optional float heuristic_factor = 2 [default = 1];
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_heuristic_factor(), target);
  }

  // optional float goal_search_tolerance = 3 [default = 0.25];
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(3, this->_internal_goal_search_tolerance(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:roborts_global_planner.AStarPlannerConfig)
  return target;
}

size_t AStarPlannerConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:roborts_global_planner.AStarPlannerConfig)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional float goal_search_tolerance = 3 [default = 0.25];
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + 4;
    }

    // optional uint32 inaccessible_cost = 1 [default = 253];
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_inaccessible_cost());
    }

    // optional float heuristic_factor = 2 [default = 1];
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + 4;
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AStarPlannerConfig::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AStarPlannerConfig::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AStarPlannerConfig::GetClassData() const { return &_class_data_; }


void AStarPlannerConfig::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AStarPlannerConfig*>(&to_msg);
  auto& from = static_cast<const AStarPlannerConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:roborts_global_planner.AStarPlannerConfig)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.goal_search_tolerance_ = from._impl_.goal_search_tolerance_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.inaccessible_cost_ = from._impl_.inaccessible_cost_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.heuristic_factor_ = from._impl_.heuristic_factor_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AStarPlannerConfig::CopyFrom(const AStarPlannerConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:roborts_global_planner.AStarPlannerConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AStarPlannerConfig::IsInitialized() const {
  return true;
}

void AStarPlannerConfig::InternalSwap(AStarPlannerConfig* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.goal_search_tolerance_, other->_impl_.goal_search_tolerance_);
  swap(_impl_.inaccessible_cost_, other->_impl_.inaccessible_cost_);
  swap(_impl_.heuristic_factor_, other->_impl_.heuristic_factor_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AStarPlannerConfig::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_a_5fstar_5fplanner_5fconfig_2eproto_getter, &descriptor_table_a_5fstar_5fplanner_5fconfig_2eproto_once,
      file_level_metadata_a_5fstar_5fplanner_5fconfig_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace roborts_global_planner
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::roborts_global_planner::AStarPlannerConfig*
Arena::CreateMaybeMessage< ::roborts_global_planner::AStarPlannerConfig >(Arena* arena) {
  return Arena::CreateMessageInternal< ::roborts_global_planner::AStarPlannerConfig >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
