// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: local_planner.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_local_5fplanner_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_local_5fplanner_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_local_5fplanner_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_local_5fplanner_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_local_5fplanner_2eproto;
namespace roborts_local_planner {
class LocalAlgorithms;
struct LocalAlgorithmsDefaultTypeInternal;
extern LocalAlgorithmsDefaultTypeInternal _LocalAlgorithms_default_instance_;
}  // namespace roborts_local_planner
PROTOBUF_NAMESPACE_OPEN
template<> ::roborts_local_planner::LocalAlgorithms* Arena::CreateMaybeMessage<::roborts_local_planner::LocalAlgorithms>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace roborts_local_planner {

// ===================================================================

class LocalAlgorithms final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:roborts_local_planner.LocalAlgorithms) */ {
 public:
  inline LocalAlgorithms() : LocalAlgorithms(nullptr) {}
  ~LocalAlgorithms() override;
  explicit PROTOBUF_CONSTEXPR LocalAlgorithms(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LocalAlgorithms(const LocalAlgorithms& from);
  LocalAlgorithms(LocalAlgorithms&& from) noexcept
    : LocalAlgorithms() {
    *this = ::std::move(from);
  }

  inline LocalAlgorithms& operator=(const LocalAlgorithms& from) {
    CopyFrom(from);
    return *this;
  }
  inline LocalAlgorithms& operator=(LocalAlgorithms&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LocalAlgorithms& default_instance() {
    return *internal_default_instance();
  }
  static inline const LocalAlgorithms* internal_default_instance() {
    return reinterpret_cast<const LocalAlgorithms*>(
               &_LocalAlgorithms_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LocalAlgorithms& a, LocalAlgorithms& b) {
    a.Swap(&b);
  }
  inline void Swap(LocalAlgorithms* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LocalAlgorithms* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LocalAlgorithms* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LocalAlgorithms>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LocalAlgorithms& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LocalAlgorithms& from) {
    LocalAlgorithms::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LocalAlgorithms* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "roborts_local_planner.LocalAlgorithms";
  }
  protected:
  explicit LocalAlgorithms(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kSelectedAlgorithmFieldNumber = 2,
    kFrequencyFieldNumber = 3,
  };
  // repeated string name = 1;
  int name_size() const;
  private:
  int _internal_name_size() const;
  public:
  void clear_name();
  const std::string& name(int index) const;
  std::string* mutable_name(int index);
  void set_name(int index, const std::string& value);
  void set_name(int index, std::string&& value);
  void set_name(int index, const char* value);
  void set_name(int index, const char* value, size_t size);
  std::string* add_name();
  void add_name(const std::string& value);
  void add_name(std::string&& value);
  void add_name(const char* value);
  void add_name(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& name() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_name();
  private:
  const std::string& _internal_name(int index) const;
  std::string* _internal_add_name();
  public:

  // optional string selected_algorithm = 2;
  bool has_selected_algorithm() const;
  private:
  bool _internal_has_selected_algorithm() const;
  public:
  void clear_selected_algorithm();
  const std::string& selected_algorithm() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_selected_algorithm(ArgT0&& arg0, ArgT... args);
  std::string* mutable_selected_algorithm();
  PROTOBUF_NODISCARD std::string* release_selected_algorithm();
  void set_allocated_selected_algorithm(std::string* selected_algorithm);
  private:
  const std::string& _internal_selected_algorithm() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_selected_algorithm(const std::string& value);
  std::string* _internal_mutable_selected_algorithm();
  public:

  // optional double frequency = 3;
  bool has_frequency() const;
  private:
  bool _internal_has_frequency() const;
  public:
  void clear_frequency();
  double frequency() const;
  void set_frequency(double value);
  private:
  double _internal_frequency() const;
  void _internal_set_frequency(double value);
  public:

  // @@protoc_insertion_point(class_scope:roborts_local_planner.LocalAlgorithms)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr selected_algorithm_;
    double frequency_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_local_5fplanner_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LocalAlgorithms

// repeated string name = 1;
inline int LocalAlgorithms::_internal_name_size() const {
  return _impl_.name_.size();
}
inline int LocalAlgorithms::name_size() const {
  return _internal_name_size();
}
inline void LocalAlgorithms::clear_name() {
  _impl_.name_.Clear();
}
inline std::string* LocalAlgorithms::add_name() {
  std::string* _s = _internal_add_name();
  // @@protoc_insertion_point(field_add_mutable:roborts_local_planner.LocalAlgorithms.name)
  return _s;
}
inline const std::string& LocalAlgorithms::_internal_name(int index) const {
  return _impl_.name_.Get(index);
}
inline const std::string& LocalAlgorithms::name(int index) const {
  // @@protoc_insertion_point(field_get:roborts_local_planner.LocalAlgorithms.name)
  return _internal_name(index);
}
inline std::string* LocalAlgorithms::mutable_name(int index) {
  // @@protoc_insertion_point(field_mutable:roborts_local_planner.LocalAlgorithms.name)
  return _impl_.name_.Mutable(index);
}
inline void LocalAlgorithms::set_name(int index, const std::string& value) {
  _impl_.name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:roborts_local_planner.LocalAlgorithms.name)
}
inline void LocalAlgorithms::set_name(int index, std::string&& value) {
  _impl_.name_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:roborts_local_planner.LocalAlgorithms.name)
}
inline void LocalAlgorithms::set_name(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:roborts_local_planner.LocalAlgorithms.name)
}
inline void LocalAlgorithms::set_name(int index, const char* value, size_t size) {
  _impl_.name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:roborts_local_planner.LocalAlgorithms.name)
}
inline std::string* LocalAlgorithms::_internal_add_name() {
  return _impl_.name_.Add();
}
inline void LocalAlgorithms::add_name(const std::string& value) {
  _impl_.name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:roborts_local_planner.LocalAlgorithms.name)
}
inline void LocalAlgorithms::add_name(std::string&& value) {
  _impl_.name_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:roborts_local_planner.LocalAlgorithms.name)
}
inline void LocalAlgorithms::add_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:roborts_local_planner.LocalAlgorithms.name)
}
inline void LocalAlgorithms::add_name(const char* value, size_t size) {
  _impl_.name_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:roborts_local_planner.LocalAlgorithms.name)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
LocalAlgorithms::name() const {
  // @@protoc_insertion_point(field_list:roborts_local_planner.LocalAlgorithms.name)
  return _impl_.name_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
LocalAlgorithms::mutable_name() {
  // @@protoc_insertion_point(field_mutable_list:roborts_local_planner.LocalAlgorithms.name)
  return &_impl_.name_;
}

// optional string selected_algorithm = 2;
inline bool LocalAlgorithms::_internal_has_selected_algorithm() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool LocalAlgorithms::has_selected_algorithm() const {
  return _internal_has_selected_algorithm();
}
inline void LocalAlgorithms::clear_selected_algorithm() {
  _impl_.selected_algorithm_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& LocalAlgorithms::selected_algorithm() const {
  // @@protoc_insertion_point(field_get:roborts_local_planner.LocalAlgorithms.selected_algorithm)
  return _internal_selected_algorithm();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LocalAlgorithms::set_selected_algorithm(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.selected_algorithm_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:roborts_local_planner.LocalAlgorithms.selected_algorithm)
}
inline std::string* LocalAlgorithms::mutable_selected_algorithm() {
  std::string* _s = _internal_mutable_selected_algorithm();
  // @@protoc_insertion_point(field_mutable:roborts_local_planner.LocalAlgorithms.selected_algorithm)
  return _s;
}
inline const std::string& LocalAlgorithms::_internal_selected_algorithm() const {
  return _impl_.selected_algorithm_.Get();
}
inline void LocalAlgorithms::_internal_set_selected_algorithm(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.selected_algorithm_.Set(value, GetArenaForAllocation());
}
inline std::string* LocalAlgorithms::_internal_mutable_selected_algorithm() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.selected_algorithm_.Mutable(GetArenaForAllocation());
}
inline std::string* LocalAlgorithms::release_selected_algorithm() {
  // @@protoc_insertion_point(field_release:roborts_local_planner.LocalAlgorithms.selected_algorithm)
  if (!_internal_has_selected_algorithm()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.selected_algorithm_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.selected_algorithm_.IsDefault()) {
    _impl_.selected_algorithm_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void LocalAlgorithms::set_allocated_selected_algorithm(std::string* selected_algorithm) {
  if (selected_algorithm != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.selected_algorithm_.SetAllocated(selected_algorithm, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.selected_algorithm_.IsDefault()) {
    _impl_.selected_algorithm_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:roborts_local_planner.LocalAlgorithms.selected_algorithm)
}

// optional double frequency = 3;
inline bool LocalAlgorithms::_internal_has_frequency() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool LocalAlgorithms::has_frequency() const {
  return _internal_has_frequency();
}
inline void LocalAlgorithms::clear_frequency() {
  _impl_.frequency_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline double LocalAlgorithms::_internal_frequency() const {
  return _impl_.frequency_;
}
inline double LocalAlgorithms::frequency() const {
  // @@protoc_insertion_point(field_get:roborts_local_planner.LocalAlgorithms.frequency)
  return _internal_frequency();
}
inline void LocalAlgorithms::_internal_set_frequency(double value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.frequency_ = value;
}
inline void LocalAlgorithms::set_frequency(double value) {
  _internal_set_frequency(value);
  // @@protoc_insertion_point(field_set:roborts_local_planner.LocalAlgorithms.frequency)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace roborts_local_planner

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_local_5fplanner_2eproto
