// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: costmap_parameter_setting.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_costmap_5fparameter_5fsetting_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_costmap_5fparameter_5fsetting_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_costmap_5fparameter_5fsetting_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_costmap_5fparameter_5fsetting_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_costmap_5fparameter_5fsetting_2eproto;
namespace roborts_costmap {
class Footprint;
struct FootprintDefaultTypeInternal;
extern FootprintDefaultTypeInternal _Footprint_default_instance_;
class ParaBasic;
struct ParaBasicDefaultTypeInternal;
extern ParaBasicDefaultTypeInternal _ParaBasic_default_instance_;
class ParaCollection;
struct ParaCollectionDefaultTypeInternal;
extern ParaCollectionDefaultTypeInternal _ParaCollection_default_instance_;
class ParaCostmapInterface;
struct ParaCostmapInterfaceDefaultTypeInternal;
extern ParaCostmapInterfaceDefaultTypeInternal _ParaCostmapInterface_default_instance_;
class Point;
struct PointDefaultTypeInternal;
extern PointDefaultTypeInternal _Point_default_instance_;
}  // namespace roborts_costmap
PROTOBUF_NAMESPACE_OPEN
template<> ::roborts_costmap::Footprint* Arena::CreateMaybeMessage<::roborts_costmap::Footprint>(Arena*);
template<> ::roborts_costmap::ParaBasic* Arena::CreateMaybeMessage<::roborts_costmap::ParaBasic>(Arena*);
template<> ::roborts_costmap::ParaCollection* Arena::CreateMaybeMessage<::roborts_costmap::ParaCollection>(Arena*);
template<> ::roborts_costmap::ParaCostmapInterface* Arena::CreateMaybeMessage<::roborts_costmap::ParaCostmapInterface>(Arena*);
template<> ::roborts_costmap::Point* Arena::CreateMaybeMessage<::roborts_costmap::Point>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace roborts_costmap {

// ===================================================================

class ParaBasic final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:roborts_costmap.ParaBasic) */ {
 public:
  inline ParaBasic() : ParaBasic(nullptr) {}
  ~ParaBasic() override;
  explicit PROTOBUF_CONSTEXPR ParaBasic(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ParaBasic(const ParaBasic& from);
  ParaBasic(ParaBasic&& from) noexcept
    : ParaBasic() {
    *this = ::std::move(from);
  }

  inline ParaBasic& operator=(const ParaBasic& from) {
    CopyFrom(from);
    return *this;
  }
  inline ParaBasic& operator=(ParaBasic&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ParaBasic& default_instance() {
    return *internal_default_instance();
  }
  static inline const ParaBasic* internal_default_instance() {
    return reinterpret_cast<const ParaBasic*>(
               &_ParaBasic_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ParaBasic& a, ParaBasic& b) {
    a.Swap(&b);
  }
  inline void Swap(ParaBasic* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ParaBasic* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ParaBasic* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ParaBasic>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ParaBasic& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ParaBasic& from) {
    ParaBasic::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ParaBasic* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "roborts_costmap.ParaBasic";
  }
  protected:
  explicit ParaBasic(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIsRawRosmessageFieldNumber = 1,
    kIsDebugFieldNumber = 2,
  };
  // required bool is_raw_rosmessage = 1;
  bool has_is_raw_rosmessage() const;
  private:
  bool _internal_has_is_raw_rosmessage() const;
  public:
  void clear_is_raw_rosmessage();
  bool is_raw_rosmessage() const;
  void set_is_raw_rosmessage(bool value);
  private:
  bool _internal_is_raw_rosmessage() const;
  void _internal_set_is_raw_rosmessage(bool value);
  public:

  // optional bool is_debug = 2;
  bool has_is_debug() const;
  private:
  bool _internal_has_is_debug() const;
  public:
  void clear_is_debug();
  bool is_debug() const;
  void set_is_debug(bool value);
  private:
  bool _internal_is_debug() const;
  void _internal_set_is_debug(bool value);
  public:

  // @@protoc_insertion_point(class_scope:roborts_costmap.ParaBasic)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    bool is_raw_rosmessage_;
    bool is_debug_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_costmap_5fparameter_5fsetting_2eproto;
};
// -------------------------------------------------------------------

class ParaCostmapInterface final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:roborts_costmap.ParaCostmapInterface) */ {
 public:
  inline ParaCostmapInterface() : ParaCostmapInterface(nullptr) {}
  ~ParaCostmapInterface() override;
  explicit PROTOBUF_CONSTEXPR ParaCostmapInterface(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ParaCostmapInterface(const ParaCostmapInterface& from);
  ParaCostmapInterface(ParaCostmapInterface&& from) noexcept
    : ParaCostmapInterface() {
    *this = ::std::move(from);
  }

  inline ParaCostmapInterface& operator=(const ParaCostmapInterface& from) {
    CopyFrom(from);
    return *this;
  }
  inline ParaCostmapInterface& operator=(ParaCostmapInterface&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ParaCostmapInterface& default_instance() {
    return *internal_default_instance();
  }
  static inline const ParaCostmapInterface* internal_default_instance() {
    return reinterpret_cast<const ParaCostmapInterface*>(
               &_ParaCostmapInterface_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ParaCostmapInterface& a, ParaCostmapInterface& b) {
    a.Swap(&b);
  }
  inline void Swap(ParaCostmapInterface* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ParaCostmapInterface* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ParaCostmapInterface* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ParaCostmapInterface>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ParaCostmapInterface& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ParaCostmapInterface& from) {
    ParaCostmapInterface::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ParaCostmapInterface* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "roborts_costmap.ParaCostmapInterface";
  }
  protected:
  explicit ParaCostmapInterface(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGlobalFrameFieldNumber = 1,
    kRobotBaseFrameFieldNumber = 2,
    kInflationFilePathFieldNumber = 15,
    kFootprintPaddingFieldNumber = 3,
    kTransformToleranceFieldNumber = 4,
    kDistanceThresholdFieldNumber = 5,
    kMapWidthFieldNumber = 6,
    kMapHeightFieldNumber = 7,
    kMapOriginXFieldNumber = 8,
    kMapOriginYFieldNumber = 9,
    kMapResolutionFieldNumber = 10,
    kMapUpdateFrequencyFieldNumber = 16,
    kIsTrackingUnknownFieldNumber = 11,
    kIsRollingWindowFieldNumber = 12,
    kHasObstacleLayerFieldNumber = 13,
    kHasStaticLayerFieldNumber = 14,
  };
  // required string global_frame = 1;
  bool has_global_frame() const;
  private:
  bool _internal_has_global_frame() const;
  public:
  void clear_global_frame();
  const std::string& global_frame() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_global_frame(ArgT0&& arg0, ArgT... args);
  std::string* mutable_global_frame();
  PROTOBUF_NODISCARD std::string* release_global_frame();
  void set_allocated_global_frame(std::string* global_frame);
  private:
  const std::string& _internal_global_frame() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_global_frame(const std::string& value);
  std::string* _internal_mutable_global_frame();
  public:

  // required string robot_base_frame = 2;
  bool has_robot_base_frame() const;
  private:
  bool _internal_has_robot_base_frame() const;
  public:
  void clear_robot_base_frame();
  const std::string& robot_base_frame() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_robot_base_frame(ArgT0&& arg0, ArgT... args);
  std::string* mutable_robot_base_frame();
  PROTOBUF_NODISCARD std::string* release_robot_base_frame();
  void set_allocated_robot_base_frame(std::string* robot_base_frame);
  private:
  const std::string& _internal_robot_base_frame() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_robot_base_frame(const std::string& value);
  std::string* _internal_mutable_robot_base_frame();
  public:

  // required string inflation_file_path = 15;
  bool has_inflation_file_path() const;
  private:
  bool _internal_has_inflation_file_path() const;
  public:
  void clear_inflation_file_path();
  const std::string& inflation_file_path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_inflation_file_path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_inflation_file_path();
  PROTOBUF_NODISCARD std::string* release_inflation_file_path();
  void set_allocated_inflation_file_path(std::string* inflation_file_path);
  private:
  const std::string& _internal_inflation_file_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_inflation_file_path(const std::string& value);
  std::string* _internal_mutable_inflation_file_path();
  public:

  // required double footprint_padding = 3;
  bool has_footprint_padding() const;
  private:
  bool _internal_has_footprint_padding() const;
  public:
  void clear_footprint_padding();
  double footprint_padding() const;
  void set_footprint_padding(double value);
  private:
  double _internal_footprint_padding() const;
  void _internal_set_footprint_padding(double value);
  public:

  // required double transform_tolerance = 4;
  bool has_transform_tolerance() const;
  private:
  bool _internal_has_transform_tolerance() const;
  public:
  void clear_transform_tolerance();
  double transform_tolerance() const;
  void set_transform_tolerance(double value);
  private:
  double _internal_transform_tolerance() const;
  void _internal_set_transform_tolerance(double value);
  public:

  // required double distance_threshold = 5;
  bool has_distance_threshold() const;
  private:
  bool _internal_has_distance_threshold() const;
  public:
  void clear_distance_threshold();
  double distance_threshold() const;
  void set_distance_threshold(double value);
  private:
  double _internal_distance_threshold() const;
  void _internal_set_distance_threshold(double value);
  public:

  // required double map_width = 6;
  bool has_map_width() const;
  private:
  bool _internal_has_map_width() const;
  public:
  void clear_map_width();
  double map_width() const;
  void set_map_width(double value);
  private:
  double _internal_map_width() const;
  void _internal_set_map_width(double value);
  public:

  // required double map_height = 7;
  bool has_map_height() const;
  private:
  bool _internal_has_map_height() const;
  public:
  void clear_map_height();
  double map_height() const;
  void set_map_height(double value);
  private:
  double _internal_map_height() const;
  void _internal_set_map_height(double value);
  public:

  // required double map_origin_x = 8;
  bool has_map_origin_x() const;
  private:
  bool _internal_has_map_origin_x() const;
  public:
  void clear_map_origin_x();
  double map_origin_x() const;
  void set_map_origin_x(double value);
  private:
  double _internal_map_origin_x() const;
  void _internal_set_map_origin_x(double value);
  public:

  // required double map_origin_y = 9;
  bool has_map_origin_y() const;
  private:
  bool _internal_has_map_origin_y() const;
  public:
  void clear_map_origin_y();
  double map_origin_y() const;
  void set_map_origin_y(double value);
  private:
  double _internal_map_origin_y() const;
  void _internal_set_map_origin_y(double value);
  public:

  // required double map_resolution = 10;
  bool has_map_resolution() const;
  private:
  bool _internal_has_map_resolution() const;
  public:
  void clear_map_resolution();
  double map_resolution() const;
  void set_map_resolution(double value);
  private:
  double _internal_map_resolution() const;
  void _internal_set_map_resolution(double value);
  public:

  // required double map_update_frequency = 16;
  bool has_map_update_frequency() const;
  private:
  bool _internal_has_map_update_frequency() const;
  public:
  void clear_map_update_frequency();
  double map_update_frequency() const;
  void set_map_update_frequency(double value);
  private:
  double _internal_map_update_frequency() const;
  void _internal_set_map_update_frequency(double value);
  public:

  // required bool is_tracking_unknown = 11;
  bool has_is_tracking_unknown() const;
  private:
  bool _internal_has_is_tracking_unknown() const;
  public:
  void clear_is_tracking_unknown();
  bool is_tracking_unknown() const;
  void set_is_tracking_unknown(bool value);
  private:
  bool _internal_is_tracking_unknown() const;
  void _internal_set_is_tracking_unknown(bool value);
  public:

  // required bool is_rolling_window = 12;
  bool has_is_rolling_window() const;
  private:
  bool _internal_has_is_rolling_window() const;
  public:
  void clear_is_rolling_window();
  bool is_rolling_window() const;
  void set_is_rolling_window(bool value);
  private:
  bool _internal_is_rolling_window() const;
  void _internal_set_is_rolling_window(bool value);
  public:

  // required bool has_obstacle_layer = 13;
  bool has_has_obstacle_layer() const;
  private:
  bool _internal_has_has_obstacle_layer() const;
  public:
  void clear_has_obstacle_layer();
  bool has_obstacle_layer() const;
  void set_has_obstacle_layer(bool value);
  private:
  bool _internal_has_obstacle_layer() const;
  void _internal_set_has_obstacle_layer(bool value);
  public:

  // required bool has_static_layer = 14;
  bool has_has_static_layer() const;
  private:
  bool _internal_has_has_static_layer() const;
  public:
  void clear_has_static_layer();
  bool has_static_layer() const;
  void set_has_static_layer(bool value);
  private:
  bool _internal_has_static_layer() const;
  void _internal_set_has_static_layer(bool value);
  public:

  // @@protoc_insertion_point(class_scope:roborts_costmap.ParaCostmapInterface)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr global_frame_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr robot_base_frame_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr inflation_file_path_;
    double footprint_padding_;
    double transform_tolerance_;
    double distance_threshold_;
    double map_width_;
    double map_height_;
    double map_origin_x_;
    double map_origin_y_;
    double map_resolution_;
    double map_update_frequency_;
    bool is_tracking_unknown_;
    bool is_rolling_window_;
    bool has_obstacle_layer_;
    bool has_static_layer_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_costmap_5fparameter_5fsetting_2eproto;
};
// -------------------------------------------------------------------

class Point final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:roborts_costmap.Point) */ {
 public:
  inline Point() : Point(nullptr) {}
  ~Point() override;
  explicit PROTOBUF_CONSTEXPR Point(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Point(const Point& from);
  Point(Point&& from) noexcept
    : Point() {
    *this = ::std::move(from);
  }

  inline Point& operator=(const Point& from) {
    CopyFrom(from);
    return *this;
  }
  inline Point& operator=(Point&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Point& default_instance() {
    return *internal_default_instance();
  }
  static inline const Point* internal_default_instance() {
    return reinterpret_cast<const Point*>(
               &_Point_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Point& a, Point& b) {
    a.Swap(&b);
  }
  inline void Swap(Point* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Point* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Point* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Point>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Point& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Point& from) {
    Point::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Point* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "roborts_costmap.Point";
  }
  protected:
  explicit Point(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // required double x = 1;
  bool has_x() const;
  private:
  bool _internal_has_x() const;
  public:
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // required double y = 2;
  bool has_y() const;
  private:
  bool _internal_has_y() const;
  public:
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // @@protoc_insertion_point(class_scope:roborts_costmap.Point)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    double x_;
    double y_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_costmap_5fparameter_5fsetting_2eproto;
};
// -------------------------------------------------------------------

class Footprint final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:roborts_costmap.Footprint) */ {
 public:
  inline Footprint() : Footprint(nullptr) {}
  ~Footprint() override;
  explicit PROTOBUF_CONSTEXPR Footprint(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Footprint(const Footprint& from);
  Footprint(Footprint&& from) noexcept
    : Footprint() {
    *this = ::std::move(from);
  }

  inline Footprint& operator=(const Footprint& from) {
    CopyFrom(from);
    return *this;
  }
  inline Footprint& operator=(Footprint&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Footprint& default_instance() {
    return *internal_default_instance();
  }
  static inline const Footprint* internal_default_instance() {
    return reinterpret_cast<const Footprint*>(
               &_Footprint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Footprint& a, Footprint& b) {
    a.Swap(&b);
  }
  inline void Swap(Footprint* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Footprint* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Footprint* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Footprint>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Footprint& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Footprint& from) {
    Footprint::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Footprint* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "roborts_costmap.Footprint";
  }
  protected:
  explicit Footprint(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPointFieldNumber = 1,
  };
  // repeated .roborts_costmap.Point point = 1;
  int point_size() const;
  private:
  int _internal_point_size() const;
  public:
  void clear_point();
  ::roborts_costmap::Point* mutable_point(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::roborts_costmap::Point >*
      mutable_point();
  private:
  const ::roborts_costmap::Point& _internal_point(int index) const;
  ::roborts_costmap::Point* _internal_add_point();
  public:
  const ::roborts_costmap::Point& point(int index) const;
  ::roborts_costmap::Point* add_point();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::roborts_costmap::Point >&
      point() const;

  // @@protoc_insertion_point(class_scope:roborts_costmap.Footprint)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::roborts_costmap::Point > point_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_costmap_5fparameter_5fsetting_2eproto;
};
// -------------------------------------------------------------------

class ParaCollection final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:roborts_costmap.ParaCollection) */ {
 public:
  inline ParaCollection() : ParaCollection(nullptr) {}
  ~ParaCollection() override;
  explicit PROTOBUF_CONSTEXPR ParaCollection(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ParaCollection(const ParaCollection& from);
  ParaCollection(ParaCollection&& from) noexcept
    : ParaCollection() {
    *this = ::std::move(from);
  }

  inline ParaCollection& operator=(const ParaCollection& from) {
    CopyFrom(from);
    return *this;
  }
  inline ParaCollection& operator=(ParaCollection&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ParaCollection& default_instance() {
    return *internal_default_instance();
  }
  static inline const ParaCollection* internal_default_instance() {
    return reinterpret_cast<const ParaCollection*>(
               &_ParaCollection_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ParaCollection& a, ParaCollection& b) {
    a.Swap(&b);
  }
  inline void Swap(ParaCollection* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ParaCollection* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ParaCollection* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ParaCollection>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ParaCollection& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ParaCollection& from) {
    ParaCollection::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ParaCollection* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "roborts_costmap.ParaCollection";
  }
  protected:
  explicit ParaCollection(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kParaCostmapInterfaceFieldNumber = 1,
    kFootprintFieldNumber = 2,
    kParaBasicFieldNumber = 3,
  };
  // required .roborts_costmap.ParaCostmapInterface para_costmap_interface = 1;
  bool has_para_costmap_interface() const;
  private:
  bool _internal_has_para_costmap_interface() const;
  public:
  void clear_para_costmap_interface();
  const ::roborts_costmap::ParaCostmapInterface& para_costmap_interface() const;
  PROTOBUF_NODISCARD ::roborts_costmap::ParaCostmapInterface* release_para_costmap_interface();
  ::roborts_costmap::ParaCostmapInterface* mutable_para_costmap_interface();
  void set_allocated_para_costmap_interface(::roborts_costmap::ParaCostmapInterface* para_costmap_interface);
  private:
  const ::roborts_costmap::ParaCostmapInterface& _internal_para_costmap_interface() const;
  ::roborts_costmap::ParaCostmapInterface* _internal_mutable_para_costmap_interface();
  public:
  void unsafe_arena_set_allocated_para_costmap_interface(
      ::roborts_costmap::ParaCostmapInterface* para_costmap_interface);
  ::roborts_costmap::ParaCostmapInterface* unsafe_arena_release_para_costmap_interface();

  // required .roborts_costmap.Footprint footprint = 2;
  bool has_footprint() const;
  private:
  bool _internal_has_footprint() const;
  public:
  void clear_footprint();
  const ::roborts_costmap::Footprint& footprint() const;
  PROTOBUF_NODISCARD ::roborts_costmap::Footprint* release_footprint();
  ::roborts_costmap::Footprint* mutable_footprint();
  void set_allocated_footprint(::roborts_costmap::Footprint* footprint);
  private:
  const ::roborts_costmap::Footprint& _internal_footprint() const;
  ::roborts_costmap::Footprint* _internal_mutable_footprint();
  public:
  void unsafe_arena_set_allocated_footprint(
      ::roborts_costmap::Footprint* footprint);
  ::roborts_costmap::Footprint* unsafe_arena_release_footprint();

  // required .roborts_costmap.ParaBasic para_basic = 3;
  bool has_para_basic() const;
  private:
  bool _internal_has_para_basic() const;
  public:
  void clear_para_basic();
  const ::roborts_costmap::ParaBasic& para_basic() const;
  PROTOBUF_NODISCARD ::roborts_costmap::ParaBasic* release_para_basic();
  ::roborts_costmap::ParaBasic* mutable_para_basic();
  void set_allocated_para_basic(::roborts_costmap::ParaBasic* para_basic);
  private:
  const ::roborts_costmap::ParaBasic& _internal_para_basic() const;
  ::roborts_costmap::ParaBasic* _internal_mutable_para_basic();
  public:
  void unsafe_arena_set_allocated_para_basic(
      ::roborts_costmap::ParaBasic* para_basic);
  ::roborts_costmap::ParaBasic* unsafe_arena_release_para_basic();

  // @@protoc_insertion_point(class_scope:roborts_costmap.ParaCollection)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::roborts_costmap::ParaCostmapInterface* para_costmap_interface_;
    ::roborts_costmap::Footprint* footprint_;
    ::roborts_costmap::ParaBasic* para_basic_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_costmap_5fparameter_5fsetting_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ParaBasic

// required bool is_raw_rosmessage = 1;
inline bool ParaBasic::_internal_has_is_raw_rosmessage() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool ParaBasic::has_is_raw_rosmessage() const {
  return _internal_has_is_raw_rosmessage();
}
inline void ParaBasic::clear_is_raw_rosmessage() {
  _impl_.is_raw_rosmessage_ = false;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline bool ParaBasic::_internal_is_raw_rosmessage() const {
  return _impl_.is_raw_rosmessage_;
}
inline bool ParaBasic::is_raw_rosmessage() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaBasic.is_raw_rosmessage)
  return _internal_is_raw_rosmessage();
}
inline void ParaBasic::_internal_set_is_raw_rosmessage(bool value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.is_raw_rosmessage_ = value;
}
inline void ParaBasic::set_is_raw_rosmessage(bool value) {
  _internal_set_is_raw_rosmessage(value);
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaBasic.is_raw_rosmessage)
}

// optional bool is_debug = 2;
inline bool ParaBasic::_internal_has_is_debug() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool ParaBasic::has_is_debug() const {
  return _internal_has_is_debug();
}
inline void ParaBasic::clear_is_debug() {
  _impl_.is_debug_ = false;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline bool ParaBasic::_internal_is_debug() const {
  return _impl_.is_debug_;
}
inline bool ParaBasic::is_debug() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaBasic.is_debug)
  return _internal_is_debug();
}
inline void ParaBasic::_internal_set_is_debug(bool value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.is_debug_ = value;
}
inline void ParaBasic::set_is_debug(bool value) {
  _internal_set_is_debug(value);
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaBasic.is_debug)
}

// -------------------------------------------------------------------

// ParaCostmapInterface

// required string global_frame = 1;
inline bool ParaCostmapInterface::_internal_has_global_frame() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool ParaCostmapInterface::has_global_frame() const {
  return _internal_has_global_frame();
}
inline void ParaCostmapInterface::clear_global_frame() {
  _impl_.global_frame_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ParaCostmapInterface::global_frame() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaCostmapInterface.global_frame)
  return _internal_global_frame();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ParaCostmapInterface::set_global_frame(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.global_frame_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaCostmapInterface.global_frame)
}
inline std::string* ParaCostmapInterface::mutable_global_frame() {
  std::string* _s = _internal_mutable_global_frame();
  // @@protoc_insertion_point(field_mutable:roborts_costmap.ParaCostmapInterface.global_frame)
  return _s;
}
inline const std::string& ParaCostmapInterface::_internal_global_frame() const {
  return _impl_.global_frame_.Get();
}
inline void ParaCostmapInterface::_internal_set_global_frame(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.global_frame_.Set(value, GetArenaForAllocation());
}
inline std::string* ParaCostmapInterface::_internal_mutable_global_frame() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.global_frame_.Mutable(GetArenaForAllocation());
}
inline std::string* ParaCostmapInterface::release_global_frame() {
  // @@protoc_insertion_point(field_release:roborts_costmap.ParaCostmapInterface.global_frame)
  if (!_internal_has_global_frame()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.global_frame_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.global_frame_.IsDefault()) {
    _impl_.global_frame_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void ParaCostmapInterface::set_allocated_global_frame(std::string* global_frame) {
  if (global_frame != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.global_frame_.SetAllocated(global_frame, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.global_frame_.IsDefault()) {
    _impl_.global_frame_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:roborts_costmap.ParaCostmapInterface.global_frame)
}

// required string robot_base_frame = 2;
inline bool ParaCostmapInterface::_internal_has_robot_base_frame() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool ParaCostmapInterface::has_robot_base_frame() const {
  return _internal_has_robot_base_frame();
}
inline void ParaCostmapInterface::clear_robot_base_frame() {
  _impl_.robot_base_frame_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& ParaCostmapInterface::robot_base_frame() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaCostmapInterface.robot_base_frame)
  return _internal_robot_base_frame();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ParaCostmapInterface::set_robot_base_frame(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.robot_base_frame_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaCostmapInterface.robot_base_frame)
}
inline std::string* ParaCostmapInterface::mutable_robot_base_frame() {
  std::string* _s = _internal_mutable_robot_base_frame();
  // @@protoc_insertion_point(field_mutable:roborts_costmap.ParaCostmapInterface.robot_base_frame)
  return _s;
}
inline const std::string& ParaCostmapInterface::_internal_robot_base_frame() const {
  return _impl_.robot_base_frame_.Get();
}
inline void ParaCostmapInterface::_internal_set_robot_base_frame(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.robot_base_frame_.Set(value, GetArenaForAllocation());
}
inline std::string* ParaCostmapInterface::_internal_mutable_robot_base_frame() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.robot_base_frame_.Mutable(GetArenaForAllocation());
}
inline std::string* ParaCostmapInterface::release_robot_base_frame() {
  // @@protoc_insertion_point(field_release:roborts_costmap.ParaCostmapInterface.robot_base_frame)
  if (!_internal_has_robot_base_frame()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.robot_base_frame_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.robot_base_frame_.IsDefault()) {
    _impl_.robot_base_frame_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void ParaCostmapInterface::set_allocated_robot_base_frame(std::string* robot_base_frame) {
  if (robot_base_frame != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.robot_base_frame_.SetAllocated(robot_base_frame, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.robot_base_frame_.IsDefault()) {
    _impl_.robot_base_frame_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:roborts_costmap.ParaCostmapInterface.robot_base_frame)
}

// required double footprint_padding = 3;
inline bool ParaCostmapInterface::_internal_has_footprint_padding() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool ParaCostmapInterface::has_footprint_padding() const {
  return _internal_has_footprint_padding();
}
inline void ParaCostmapInterface::clear_footprint_padding() {
  _impl_.footprint_padding_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline double ParaCostmapInterface::_internal_footprint_padding() const {
  return _impl_.footprint_padding_;
}
inline double ParaCostmapInterface::footprint_padding() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaCostmapInterface.footprint_padding)
  return _internal_footprint_padding();
}
inline void ParaCostmapInterface::_internal_set_footprint_padding(double value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.footprint_padding_ = value;
}
inline void ParaCostmapInterface::set_footprint_padding(double value) {
  _internal_set_footprint_padding(value);
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaCostmapInterface.footprint_padding)
}

// required double transform_tolerance = 4;
inline bool ParaCostmapInterface::_internal_has_transform_tolerance() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool ParaCostmapInterface::has_transform_tolerance() const {
  return _internal_has_transform_tolerance();
}
inline void ParaCostmapInterface::clear_transform_tolerance() {
  _impl_.transform_tolerance_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline double ParaCostmapInterface::_internal_transform_tolerance() const {
  return _impl_.transform_tolerance_;
}
inline double ParaCostmapInterface::transform_tolerance() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaCostmapInterface.transform_tolerance)
  return _internal_transform_tolerance();
}
inline void ParaCostmapInterface::_internal_set_transform_tolerance(double value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.transform_tolerance_ = value;
}
inline void ParaCostmapInterface::set_transform_tolerance(double value) {
  _internal_set_transform_tolerance(value);
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaCostmapInterface.transform_tolerance)
}

// required double distance_threshold = 5;
inline bool ParaCostmapInterface::_internal_has_distance_threshold() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool ParaCostmapInterface::has_distance_threshold() const {
  return _internal_has_distance_threshold();
}
inline void ParaCostmapInterface::clear_distance_threshold() {
  _impl_.distance_threshold_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline double ParaCostmapInterface::_internal_distance_threshold() const {
  return _impl_.distance_threshold_;
}
inline double ParaCostmapInterface::distance_threshold() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaCostmapInterface.distance_threshold)
  return _internal_distance_threshold();
}
inline void ParaCostmapInterface::_internal_set_distance_threshold(double value) {
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.distance_threshold_ = value;
}
inline void ParaCostmapInterface::set_distance_threshold(double value) {
  _internal_set_distance_threshold(value);
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaCostmapInterface.distance_threshold)
}

// required double map_width = 6;
inline bool ParaCostmapInterface::_internal_has_map_width() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool ParaCostmapInterface::has_map_width() const {
  return _internal_has_map_width();
}
inline void ParaCostmapInterface::clear_map_width() {
  _impl_.map_width_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline double ParaCostmapInterface::_internal_map_width() const {
  return _impl_.map_width_;
}
inline double ParaCostmapInterface::map_width() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaCostmapInterface.map_width)
  return _internal_map_width();
}
inline void ParaCostmapInterface::_internal_set_map_width(double value) {
  _impl_._has_bits_[0] |= 0x00000040u;
  _impl_.map_width_ = value;
}
inline void ParaCostmapInterface::set_map_width(double value) {
  _internal_set_map_width(value);
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaCostmapInterface.map_width)
}

// required double map_height = 7;
inline bool ParaCostmapInterface::_internal_has_map_height() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool ParaCostmapInterface::has_map_height() const {
  return _internal_has_map_height();
}
inline void ParaCostmapInterface::clear_map_height() {
  _impl_.map_height_ = 0;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline double ParaCostmapInterface::_internal_map_height() const {
  return _impl_.map_height_;
}
inline double ParaCostmapInterface::map_height() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaCostmapInterface.map_height)
  return _internal_map_height();
}
inline void ParaCostmapInterface::_internal_set_map_height(double value) {
  _impl_._has_bits_[0] |= 0x00000080u;
  _impl_.map_height_ = value;
}
inline void ParaCostmapInterface::set_map_height(double value) {
  _internal_set_map_height(value);
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaCostmapInterface.map_height)
}

// required double map_origin_x = 8;
inline bool ParaCostmapInterface::_internal_has_map_origin_x() const {
  bool value = (_impl_._has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool ParaCostmapInterface::has_map_origin_x() const {
  return _internal_has_map_origin_x();
}
inline void ParaCostmapInterface::clear_map_origin_x() {
  _impl_.map_origin_x_ = 0;
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline double ParaCostmapInterface::_internal_map_origin_x() const {
  return _impl_.map_origin_x_;
}
inline double ParaCostmapInterface::map_origin_x() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaCostmapInterface.map_origin_x)
  return _internal_map_origin_x();
}
inline void ParaCostmapInterface::_internal_set_map_origin_x(double value) {
  _impl_._has_bits_[0] |= 0x00000100u;
  _impl_.map_origin_x_ = value;
}
inline void ParaCostmapInterface::set_map_origin_x(double value) {
  _internal_set_map_origin_x(value);
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaCostmapInterface.map_origin_x)
}

// required double map_origin_y = 9;
inline bool ParaCostmapInterface::_internal_has_map_origin_y() const {
  bool value = (_impl_._has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool ParaCostmapInterface::has_map_origin_y() const {
  return _internal_has_map_origin_y();
}
inline void ParaCostmapInterface::clear_map_origin_y() {
  _impl_.map_origin_y_ = 0;
  _impl_._has_bits_[0] &= ~0x00000200u;
}
inline double ParaCostmapInterface::_internal_map_origin_y() const {
  return _impl_.map_origin_y_;
}
inline double ParaCostmapInterface::map_origin_y() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaCostmapInterface.map_origin_y)
  return _internal_map_origin_y();
}
inline void ParaCostmapInterface::_internal_set_map_origin_y(double value) {
  _impl_._has_bits_[0] |= 0x00000200u;
  _impl_.map_origin_y_ = value;
}
inline void ParaCostmapInterface::set_map_origin_y(double value) {
  _internal_set_map_origin_y(value);
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaCostmapInterface.map_origin_y)
}

// required double map_resolution = 10;
inline bool ParaCostmapInterface::_internal_has_map_resolution() const {
  bool value = (_impl_._has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline bool ParaCostmapInterface::has_map_resolution() const {
  return _internal_has_map_resolution();
}
inline void ParaCostmapInterface::clear_map_resolution() {
  _impl_.map_resolution_ = 0;
  _impl_._has_bits_[0] &= ~0x00000400u;
}
inline double ParaCostmapInterface::_internal_map_resolution() const {
  return _impl_.map_resolution_;
}
inline double ParaCostmapInterface::map_resolution() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaCostmapInterface.map_resolution)
  return _internal_map_resolution();
}
inline void ParaCostmapInterface::_internal_set_map_resolution(double value) {
  _impl_._has_bits_[0] |= 0x00000400u;
  _impl_.map_resolution_ = value;
}
inline void ParaCostmapInterface::set_map_resolution(double value) {
  _internal_set_map_resolution(value);
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaCostmapInterface.map_resolution)
}

// required bool is_tracking_unknown = 11;
inline bool ParaCostmapInterface::_internal_has_is_tracking_unknown() const {
  bool value = (_impl_._has_bits_[0] & 0x00001000u) != 0;
  return value;
}
inline bool ParaCostmapInterface::has_is_tracking_unknown() const {
  return _internal_has_is_tracking_unknown();
}
inline void ParaCostmapInterface::clear_is_tracking_unknown() {
  _impl_.is_tracking_unknown_ = false;
  _impl_._has_bits_[0] &= ~0x00001000u;
}
inline bool ParaCostmapInterface::_internal_is_tracking_unknown() const {
  return _impl_.is_tracking_unknown_;
}
inline bool ParaCostmapInterface::is_tracking_unknown() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaCostmapInterface.is_tracking_unknown)
  return _internal_is_tracking_unknown();
}
inline void ParaCostmapInterface::_internal_set_is_tracking_unknown(bool value) {
  _impl_._has_bits_[0] |= 0x00001000u;
  _impl_.is_tracking_unknown_ = value;
}
inline void ParaCostmapInterface::set_is_tracking_unknown(bool value) {
  _internal_set_is_tracking_unknown(value);
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaCostmapInterface.is_tracking_unknown)
}

// required bool is_rolling_window = 12;
inline bool ParaCostmapInterface::_internal_has_is_rolling_window() const {
  bool value = (_impl_._has_bits_[0] & 0x00002000u) != 0;
  return value;
}
inline bool ParaCostmapInterface::has_is_rolling_window() const {
  return _internal_has_is_rolling_window();
}
inline void ParaCostmapInterface::clear_is_rolling_window() {
  _impl_.is_rolling_window_ = false;
  _impl_._has_bits_[0] &= ~0x00002000u;
}
inline bool ParaCostmapInterface::_internal_is_rolling_window() const {
  return _impl_.is_rolling_window_;
}
inline bool ParaCostmapInterface::is_rolling_window() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaCostmapInterface.is_rolling_window)
  return _internal_is_rolling_window();
}
inline void ParaCostmapInterface::_internal_set_is_rolling_window(bool value) {
  _impl_._has_bits_[0] |= 0x00002000u;
  _impl_.is_rolling_window_ = value;
}
inline void ParaCostmapInterface::set_is_rolling_window(bool value) {
  _internal_set_is_rolling_window(value);
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaCostmapInterface.is_rolling_window)
}

// required bool has_obstacle_layer = 13;
inline bool ParaCostmapInterface::_internal_has_has_obstacle_layer() const {
  bool value = (_impl_._has_bits_[0] & 0x00004000u) != 0;
  return value;
}
inline bool ParaCostmapInterface::has_has_obstacle_layer() const {
  return _internal_has_has_obstacle_layer();
}
inline void ParaCostmapInterface::clear_has_obstacle_layer() {
  _impl_.has_obstacle_layer_ = false;
  _impl_._has_bits_[0] &= ~0x00004000u;
}
inline bool ParaCostmapInterface::_internal_has_obstacle_layer() const {
  return _impl_.has_obstacle_layer_;
}
inline bool ParaCostmapInterface::has_obstacle_layer() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaCostmapInterface.has_obstacle_layer)
  return _internal_has_obstacle_layer();
}
inline void ParaCostmapInterface::_internal_set_has_obstacle_layer(bool value) {
  _impl_._has_bits_[0] |= 0x00004000u;
  _impl_.has_obstacle_layer_ = value;
}
inline void ParaCostmapInterface::set_has_obstacle_layer(bool value) {
  _internal_set_has_obstacle_layer(value);
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaCostmapInterface.has_obstacle_layer)
}

// required bool has_static_layer = 14;
inline bool ParaCostmapInterface::_internal_has_has_static_layer() const {
  bool value = (_impl_._has_bits_[0] & 0x00008000u) != 0;
  return value;
}
inline bool ParaCostmapInterface::has_has_static_layer() const {
  return _internal_has_has_static_layer();
}
inline void ParaCostmapInterface::clear_has_static_layer() {
  _impl_.has_static_layer_ = false;
  _impl_._has_bits_[0] &= ~0x00008000u;
}
inline bool ParaCostmapInterface::_internal_has_static_layer() const {
  return _impl_.has_static_layer_;
}
inline bool ParaCostmapInterface::has_static_layer() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaCostmapInterface.has_static_layer)
  return _internal_has_static_layer();
}
inline void ParaCostmapInterface::_internal_set_has_static_layer(bool value) {
  _impl_._has_bits_[0] |= 0x00008000u;
  _impl_.has_static_layer_ = value;
}
inline void ParaCostmapInterface::set_has_static_layer(bool value) {
  _internal_set_has_static_layer(value);
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaCostmapInterface.has_static_layer)
}

// required string inflation_file_path = 15;
inline bool ParaCostmapInterface::_internal_has_inflation_file_path() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool ParaCostmapInterface::has_inflation_file_path() const {
  return _internal_has_inflation_file_path();
}
inline void ParaCostmapInterface::clear_inflation_file_path() {
  _impl_.inflation_file_path_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& ParaCostmapInterface::inflation_file_path() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaCostmapInterface.inflation_file_path)
  return _internal_inflation_file_path();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ParaCostmapInterface::set_inflation_file_path(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000004u;
 _impl_.inflation_file_path_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaCostmapInterface.inflation_file_path)
}
inline std::string* ParaCostmapInterface::mutable_inflation_file_path() {
  std::string* _s = _internal_mutable_inflation_file_path();
  // @@protoc_insertion_point(field_mutable:roborts_costmap.ParaCostmapInterface.inflation_file_path)
  return _s;
}
inline const std::string& ParaCostmapInterface::_internal_inflation_file_path() const {
  return _impl_.inflation_file_path_.Get();
}
inline void ParaCostmapInterface::_internal_set_inflation_file_path(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.inflation_file_path_.Set(value, GetArenaForAllocation());
}
inline std::string* ParaCostmapInterface::_internal_mutable_inflation_file_path() {
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.inflation_file_path_.Mutable(GetArenaForAllocation());
}
inline std::string* ParaCostmapInterface::release_inflation_file_path() {
  // @@protoc_insertion_point(field_release:roborts_costmap.ParaCostmapInterface.inflation_file_path)
  if (!_internal_has_inflation_file_path()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* p = _impl_.inflation_file_path_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.inflation_file_path_.IsDefault()) {
    _impl_.inflation_file_path_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void ParaCostmapInterface::set_allocated_inflation_file_path(std::string* inflation_file_path) {
  if (inflation_file_path != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.inflation_file_path_.SetAllocated(inflation_file_path, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.inflation_file_path_.IsDefault()) {
    _impl_.inflation_file_path_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:roborts_costmap.ParaCostmapInterface.inflation_file_path)
}

// required double map_update_frequency = 16;
inline bool ParaCostmapInterface::_internal_has_map_update_frequency() const {
  bool value = (_impl_._has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline bool ParaCostmapInterface::has_map_update_frequency() const {
  return _internal_has_map_update_frequency();
}
inline void ParaCostmapInterface::clear_map_update_frequency() {
  _impl_.map_update_frequency_ = 0;
  _impl_._has_bits_[0] &= ~0x00000800u;
}
inline double ParaCostmapInterface::_internal_map_update_frequency() const {
  return _impl_.map_update_frequency_;
}
inline double ParaCostmapInterface::map_update_frequency() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaCostmapInterface.map_update_frequency)
  return _internal_map_update_frequency();
}
inline void ParaCostmapInterface::_internal_set_map_update_frequency(double value) {
  _impl_._has_bits_[0] |= 0x00000800u;
  _impl_.map_update_frequency_ = value;
}
inline void ParaCostmapInterface::set_map_update_frequency(double value) {
  _internal_set_map_update_frequency(value);
  // @@protoc_insertion_point(field_set:roborts_costmap.ParaCostmapInterface.map_update_frequency)
}

// -------------------------------------------------------------------

// Point

// required double x = 1;
inline bool Point::_internal_has_x() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Point::has_x() const {
  return _internal_has_x();
}
inline void Point::clear_x() {
  _impl_.x_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline double Point::_internal_x() const {
  return _impl_.x_;
}
inline double Point::x() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.Point.x)
  return _internal_x();
}
inline void Point::_internal_set_x(double value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.x_ = value;
}
inline void Point::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:roborts_costmap.Point.x)
}

// required double y = 2;
inline bool Point::_internal_has_y() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Point::has_y() const {
  return _internal_has_y();
}
inline void Point::clear_y() {
  _impl_.y_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline double Point::_internal_y() const {
  return _impl_.y_;
}
inline double Point::y() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.Point.y)
  return _internal_y();
}
inline void Point::_internal_set_y(double value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.y_ = value;
}
inline void Point::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:roborts_costmap.Point.y)
}

// -------------------------------------------------------------------

// Footprint

// repeated .roborts_costmap.Point point = 1;
inline int Footprint::_internal_point_size() const {
  return _impl_.point_.size();
}
inline int Footprint::point_size() const {
  return _internal_point_size();
}
inline void Footprint::clear_point() {
  _impl_.point_.Clear();
}
inline ::roborts_costmap::Point* Footprint::mutable_point(int index) {
  // @@protoc_insertion_point(field_mutable:roborts_costmap.Footprint.point)
  return _impl_.point_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::roborts_costmap::Point >*
Footprint::mutable_point() {
  // @@protoc_insertion_point(field_mutable_list:roborts_costmap.Footprint.point)
  return &_impl_.point_;
}
inline const ::roborts_costmap::Point& Footprint::_internal_point(int index) const {
  return _impl_.point_.Get(index);
}
inline const ::roborts_costmap::Point& Footprint::point(int index) const {
  // @@protoc_insertion_point(field_get:roborts_costmap.Footprint.point)
  return _internal_point(index);
}
inline ::roborts_costmap::Point* Footprint::_internal_add_point() {
  return _impl_.point_.Add();
}
inline ::roborts_costmap::Point* Footprint::add_point() {
  ::roborts_costmap::Point* _add = _internal_add_point();
  // @@protoc_insertion_point(field_add:roborts_costmap.Footprint.point)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::roborts_costmap::Point >&
Footprint::point() const {
  // @@protoc_insertion_point(field_list:roborts_costmap.Footprint.point)
  return _impl_.point_;
}

// -------------------------------------------------------------------

// ParaCollection

// required .roborts_costmap.ParaCostmapInterface para_costmap_interface = 1;
inline bool ParaCollection::_internal_has_para_costmap_interface() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.para_costmap_interface_ != nullptr);
  return value;
}
inline bool ParaCollection::has_para_costmap_interface() const {
  return _internal_has_para_costmap_interface();
}
inline void ParaCollection::clear_para_costmap_interface() {
  if (_impl_.para_costmap_interface_ != nullptr) _impl_.para_costmap_interface_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::roborts_costmap::ParaCostmapInterface& ParaCollection::_internal_para_costmap_interface() const {
  const ::roborts_costmap::ParaCostmapInterface* p = _impl_.para_costmap_interface_;
  return p != nullptr ? *p : reinterpret_cast<const ::roborts_costmap::ParaCostmapInterface&>(
      ::roborts_costmap::_ParaCostmapInterface_default_instance_);
}
inline const ::roborts_costmap::ParaCostmapInterface& ParaCollection::para_costmap_interface() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaCollection.para_costmap_interface)
  return _internal_para_costmap_interface();
}
inline void ParaCollection::unsafe_arena_set_allocated_para_costmap_interface(
    ::roborts_costmap::ParaCostmapInterface* para_costmap_interface) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.para_costmap_interface_);
  }
  _impl_.para_costmap_interface_ = para_costmap_interface;
  if (para_costmap_interface) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:roborts_costmap.ParaCollection.para_costmap_interface)
}
inline ::roborts_costmap::ParaCostmapInterface* ParaCollection::release_para_costmap_interface() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::roborts_costmap::ParaCostmapInterface* temp = _impl_.para_costmap_interface_;
  _impl_.para_costmap_interface_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::roborts_costmap::ParaCostmapInterface* ParaCollection::unsafe_arena_release_para_costmap_interface() {
  // @@protoc_insertion_point(field_release:roborts_costmap.ParaCollection.para_costmap_interface)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::roborts_costmap::ParaCostmapInterface* temp = _impl_.para_costmap_interface_;
  _impl_.para_costmap_interface_ = nullptr;
  return temp;
}
inline ::roborts_costmap::ParaCostmapInterface* ParaCollection::_internal_mutable_para_costmap_interface() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.para_costmap_interface_ == nullptr) {
    auto* p = CreateMaybeMessage<::roborts_costmap::ParaCostmapInterface>(GetArenaForAllocation());
    _impl_.para_costmap_interface_ = p;
  }
  return _impl_.para_costmap_interface_;
}
inline ::roborts_costmap::ParaCostmapInterface* ParaCollection::mutable_para_costmap_interface() {
  ::roborts_costmap::ParaCostmapInterface* _msg = _internal_mutable_para_costmap_interface();
  // @@protoc_insertion_point(field_mutable:roborts_costmap.ParaCollection.para_costmap_interface)
  return _msg;
}
inline void ParaCollection::set_allocated_para_costmap_interface(::roborts_costmap::ParaCostmapInterface* para_costmap_interface) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.para_costmap_interface_;
  }
  if (para_costmap_interface) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(para_costmap_interface);
    if (message_arena != submessage_arena) {
      para_costmap_interface = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, para_costmap_interface, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.para_costmap_interface_ = para_costmap_interface;
  // @@protoc_insertion_point(field_set_allocated:roborts_costmap.ParaCollection.para_costmap_interface)
}

// required .roborts_costmap.Footprint footprint = 2;
inline bool ParaCollection::_internal_has_footprint() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.footprint_ != nullptr);
  return value;
}
inline bool ParaCollection::has_footprint() const {
  return _internal_has_footprint();
}
inline void ParaCollection::clear_footprint() {
  if (_impl_.footprint_ != nullptr) _impl_.footprint_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::roborts_costmap::Footprint& ParaCollection::_internal_footprint() const {
  const ::roborts_costmap::Footprint* p = _impl_.footprint_;
  return p != nullptr ? *p : reinterpret_cast<const ::roborts_costmap::Footprint&>(
      ::roborts_costmap::_Footprint_default_instance_);
}
inline const ::roborts_costmap::Footprint& ParaCollection::footprint() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaCollection.footprint)
  return _internal_footprint();
}
inline void ParaCollection::unsafe_arena_set_allocated_footprint(
    ::roborts_costmap::Footprint* footprint) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.footprint_);
  }
  _impl_.footprint_ = footprint;
  if (footprint) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:roborts_costmap.ParaCollection.footprint)
}
inline ::roborts_costmap::Footprint* ParaCollection::release_footprint() {
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::roborts_costmap::Footprint* temp = _impl_.footprint_;
  _impl_.footprint_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::roborts_costmap::Footprint* ParaCollection::unsafe_arena_release_footprint() {
  // @@protoc_insertion_point(field_release:roborts_costmap.ParaCollection.footprint)
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::roborts_costmap::Footprint* temp = _impl_.footprint_;
  _impl_.footprint_ = nullptr;
  return temp;
}
inline ::roborts_costmap::Footprint* ParaCollection::_internal_mutable_footprint() {
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.footprint_ == nullptr) {
    auto* p = CreateMaybeMessage<::roborts_costmap::Footprint>(GetArenaForAllocation());
    _impl_.footprint_ = p;
  }
  return _impl_.footprint_;
}
inline ::roborts_costmap::Footprint* ParaCollection::mutable_footprint() {
  ::roborts_costmap::Footprint* _msg = _internal_mutable_footprint();
  // @@protoc_insertion_point(field_mutable:roborts_costmap.ParaCollection.footprint)
  return _msg;
}
inline void ParaCollection::set_allocated_footprint(::roborts_costmap::Footprint* footprint) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.footprint_;
  }
  if (footprint) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(footprint);
    if (message_arena != submessage_arena) {
      footprint = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, footprint, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.footprint_ = footprint;
  // @@protoc_insertion_point(field_set_allocated:roborts_costmap.ParaCollection.footprint)
}

// required .roborts_costmap.ParaBasic para_basic = 3;
inline bool ParaCollection::_internal_has_para_basic() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.para_basic_ != nullptr);
  return value;
}
inline bool ParaCollection::has_para_basic() const {
  return _internal_has_para_basic();
}
inline void ParaCollection::clear_para_basic() {
  if (_impl_.para_basic_ != nullptr) _impl_.para_basic_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const ::roborts_costmap::ParaBasic& ParaCollection::_internal_para_basic() const {
  const ::roborts_costmap::ParaBasic* p = _impl_.para_basic_;
  return p != nullptr ? *p : reinterpret_cast<const ::roborts_costmap::ParaBasic&>(
      ::roborts_costmap::_ParaBasic_default_instance_);
}
inline const ::roborts_costmap::ParaBasic& ParaCollection::para_basic() const {
  // @@protoc_insertion_point(field_get:roborts_costmap.ParaCollection.para_basic)
  return _internal_para_basic();
}
inline void ParaCollection::unsafe_arena_set_allocated_para_basic(
    ::roborts_costmap::ParaBasic* para_basic) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.para_basic_);
  }
  _impl_.para_basic_ = para_basic;
  if (para_basic) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:roborts_costmap.ParaCollection.para_basic)
}
inline ::roborts_costmap::ParaBasic* ParaCollection::release_para_basic() {
  _impl_._has_bits_[0] &= ~0x00000004u;
  ::roborts_costmap::ParaBasic* temp = _impl_.para_basic_;
  _impl_.para_basic_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::roborts_costmap::ParaBasic* ParaCollection::unsafe_arena_release_para_basic() {
  // @@protoc_insertion_point(field_release:roborts_costmap.ParaCollection.para_basic)
  _impl_._has_bits_[0] &= ~0x00000004u;
  ::roborts_costmap::ParaBasic* temp = _impl_.para_basic_;
  _impl_.para_basic_ = nullptr;
  return temp;
}
inline ::roborts_costmap::ParaBasic* ParaCollection::_internal_mutable_para_basic() {
  _impl_._has_bits_[0] |= 0x00000004u;
  if (_impl_.para_basic_ == nullptr) {
    auto* p = CreateMaybeMessage<::roborts_costmap::ParaBasic>(GetArenaForAllocation());
    _impl_.para_basic_ = p;
  }
  return _impl_.para_basic_;
}
inline ::roborts_costmap::ParaBasic* ParaCollection::mutable_para_basic() {
  ::roborts_costmap::ParaBasic* _msg = _internal_mutable_para_basic();
  // @@protoc_insertion_point(field_mutable:roborts_costmap.ParaCollection.para_basic)
  return _msg;
}
inline void ParaCollection::set_allocated_para_basic(::roborts_costmap::ParaBasic* para_basic) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.para_basic_;
  }
  if (para_basic) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(para_basic);
    if (message_arena != submessage_arena) {
      para_basic = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, para_basic, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.para_basic_ = para_basic;
  // @@protoc_insertion_point(field_set_allocated:roborts_costmap.ParaCollection.para_basic)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace roborts_costmap

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_costmap_5fparameter_5fsetting_2eproto
